name: mondayd (test)

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/go-mondayd-test.yml'
      - 'go/core/cmd/mondayd/**'
      - 'go/core/lib/monday/**'
      - 'go/core/rest/monday/**'
      
  workflow_dispatch:          

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: GitHub environment
        run: |
          echo "EVENT=$GITHUB_EVENT_NAME"
          echo "REPOSITORY=$GITHUB_REPOSITORY"
          echo "WORKFLOW=$GITHUB_WORKFLOW"
          echo "RUN_NUMBER=$GITHUB_RUN_NUMBER"           
          echo "ACTOR=$GITHUB_ACTOR"
          echo "COMMIT=$GITHUB_SHA"
          echo "REF=$GITHUB_REF"
          echo "TAG=$GITHUB_REF_NAME"
    
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main      

      - name: Set Docker image build tag and image name
        run: |
          IMAGE_NAME="us-central1-docker.pkg.dev/prj-d1s-sandbox/d1stech/monday-service:main"
          echo "IMAGE_NAME=${IMAGE_NAME}" | tee -a $GITHUB_ENV      
          
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          context: ./go/core
          file: go/core/cmd/mondayd/Dockerfile-test
          tags: '${{ env.IMAGE_NAME }}'
          
      - name: Clean Docker
        run: |
          docker rmi -f "${{ env.IMAGE_NAME }}"
          docker system prune -f
