name: saged (test)

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/go-saged-test.yml'
      - 'go/core/cmd/saged/**'
      - 'go/core/lib/deepgram/**'
      - 'go/core/lib/elevenlabs/**'
      - 'go/core/lib/firebase/**'
      - 'go/core/lib/firestore/**'
      - 'go/core/lib/gcp/**'
      - 'go/core/lib/openai/**'
      - 'go/core/lib/opus/**'
      - 'go/core/lib/sage/**'
      - 'go/core/lib/stabilityai/**'
      - 'go/core/pkg/vox/**'
      - 'go/core/rest/api/**'
      - 'go/core/rest/auth/**'
      - 'go/core/rest/errors/**'
      - 'go/core/rest/firebase/**'
      - 'go/core/rest/lib/**'
      - 'go/core/rest/openai/**'
      - 'go/core/rest/sage/**'
      - 'go/core/rest/vox/**'
      
      
  workflow_dispatch:          

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: GitHub environment
        run: |
          echo "EVENT=$GITHUB_EVENT_NAME"
          echo "REPOSITORY=$GITHUB_REPOSITORY"
          echo "WORKFLOW=$GITHUB_WORKFLOW"
          echo "RUN_NUMBER=$GITHUB_RUN_NUMBER"           
          echo "ACTOR=$GITHUB_ACTOR"
          echo "COMMIT=$GITHUB_SHA"
          echo "REF=$GITHUB_REF"
          echo "TAG=$GITHUB_REF_NAME"
    
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main      

      - name: Set Docker image build tag and image name
        run: |
          IMAGE_NAME="us-central1-docker.pkg.dev/prj-d1s-sandbox/d1stech/sage-service:main"
          echo "IMAGE_NAME=${IMAGE_NAME}" | tee -a $GITHUB_ENV      
          
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          context: ./go/core
          file: go/core/cmd/saged/Dockerfile-test
          tags: '${{ env.IMAGE_NAME }}'
          
      - name: Clean Docker
        run: |
          docker rmi -f "${{ env.IMAGE_NAME }}"
          docker system prune -f
